// tokens-ok: file — every site's two colours are declared here.
import type { EcosystemSite, SiteRecord } from './types.ts';

export type {
  EcosystemSite,
  SiteId,
  SiteMarkColors,
  SiteName,
  SiteRecord,
} from './types.ts';

/**
 * Every site of the family, each with the two colours it owns. The marks that
 * go with them live in `marks.tsx`.
 */
export const ECOSYSTEM_SITES: readonly EcosystemSite[] = [
  {
    id: 'learn',
    name: { lead: 'learn', alt: 'cheminfo', dot: true },
    host: 'learn.cheminfo.org',
    repository: 'https://github.com/cheminfo/learn.cheminfo.org',
    tagline: 'Arrange the tools into a course and hand out its link.',
    group: 'computing',
    brand: '#0d9488',
    brandAlt: '#b45309',
    mark: { plate: '#0d9488', accent: '#f59e0b' },
  },
  {
    id: 'inchi',
    name: { lead: 'inchi', alt: 'cheminfo', dot: true },
    host: 'inchi.cheminfo.org',
    repository: 'https://github.com/cheminfo/inchi.cheminfo.org',
    tagline: 'InChI and InChIKey from a structure, in the browser.',
    group: 'structures',
    brand: '#5b21b6',
    brandAlt: '#a16207',
    mark: { plate: '#5b21b6', accent: '#fcd34d' },
  },
  {
    id: 'vcl',
    name: { lead: 'vcl', alt: 'cheminfo', dot: true },
    host: 'vcl.cheminfo.org',
    repository: 'https://github.com/cheminfo/vcl.cheminfo.org',
    tagline: 'Combine a core and fragments into a screened library.',
    group: 'research',
    brand: '#2d72d2',
    brandAlt: '#9a3412',
    mark: { plate: '#2d72d2', accent: '#eb6847' },
  },
  {
    id: 'smiles',
    name: { lead: 'smiles', alt: 'cheminfo', dot: true },
    host: 'smiles.cheminfo.org',
    repository: 'https://github.com/cheminfo/smiles.cheminfo.org',
    tagline: 'Draw a structure, read its SMILES, learn the notation.',
    group: 'structures',
    brand: '#1c6e42',
    brandAlt: '#9a3412',
    mark: { plate: '#1c6e42', accent: '#ea580c' },
  },
  {
    id: 'openbabel',
    name: { lead: 'openbabel', alt: 'cheminfo', dot: true },
    host: 'openbabel.cheminfo.org',
    repository: 'https://github.com/cheminfo/openbabel.cheminfo.org',
    publicRepository: true,
    tagline: 'Convert a structure between any pair of chemical file formats.',
    group: 'structures',
    brand: '#0f766e',
    brandAlt: '#c2410c',
    mark: { plate: '#0f766e', accent: '#fb923c' },
  },
  {
    id: 'chemcalc',
    name: { lead: 'Chem', alt: 'Calc' },
    host: 'www.chemcalc.org',
    repository: 'https://github.com/cheminfo/chemcalc.org',
    tagline: 'Molecular formula, exact mass and isotopic distribution.',
    group: 'basics',
    brand: '#5b52e0',
    brandAlt: '#d63384',
    mark: { plate: '#5b52e0', accent: '#ff8ac2' },
  },
  {
    id: 'dbe',
    name: { lead: 'dbe', alt: 'cheminfo', dot: true },
    host: 'dbe.cheminfo.org',
    repository: 'https://github.com/cheminfo/dbe.cheminfo.org',
    publicRepository: true,
    tagline: 'Count rings and double bonds from a formula or a structure.',
    group: 'basics',
    brand: '#63123f',
    // The emerald the mark's double bond is drawn in sits at 2.5:1 on white,
    // so the second half of the wordmark takes this darkened form instead.
    brandAlt: '#047857',
    mark: { plate: '#63123f', accent: '#10b981' },
  },
  {
    id: 'nmrium',
    name: { lead: 'NMR', alt: 'ium' },
    host: 'www.nmrium.org',
    repository: 'https://github.com/cheminfo/nmrium',
    publicRepository: true,
    tagline: 'Process and assign NMR spectra in the browser.',
    group: 'spectra',
    brand: '#ea580c',
    brandAlt: '#2b143e',
    mark: { plate: '#2b143e', accent: '#ea580c' },
  },
  {
    id: 'metabo',
    // Not `.cheminfo`: the second half of a one-word name is the domain the
    // site actually lives at, and this one is a sibling of NMRium rather than
    // of the cheminfo tools.
    name: { lead: 'metabo', alt: 'nmrium', dot: true },
    host: 'metabo.nmrium.com',
    repository: 'https://github.com/cheminfo/metabo',
    tagline: 'Turn a batch of NMR spectra into a map of your samples.',
    group: 'spectra',
    brand: '#4d7c0f',
    brandAlt: '#b91c1c',
    mark: { plate: '#4d7c0f', accent: '#b91c1c' },
  },
  {
    id: 'derepflow',
    name: { lead: 'Derep', alt: 'Flow', ink: 'lead' },
    host: 'derepflow.cheminfo.org',
    repository: 'https://github.com/cheminfo/derepflow',
    tagline: 'Identify the constituents of a mixture from its ¹³C spectrum.',
    group: 'spectra',
    brand: '#127ba3',
    brandAlt: '#1e293b',
    mark: { plate: '#1e293b', accent: '#127ba3' },
  },
  {
    id: 'surge',
    name: { lead: 'surge', alt: 'cheminfo', dot: true },
    host: 'surge.cheminfo.org',
    repository: 'https://github.com/cheminfo/surge.cheminfo.org',
    publicRepository: true,
    tagline: 'Every constitutional isomer of a molecular formula.',
    group: 'structures',
    brand: '#4338ca',
    brandAlt: '#be123c',
    mark: { plate: '#4338ca', accent: '#e11d48' },
  },
  {
    id: 'tex',
    name: { lead: 'tex', alt: 'cheminfo', dot: true },
    host: 'tex.cheminfo.org',
    repository: 'https://github.com/cheminfo/tex.cheminfo.org',
    publicRepository: true,
    tagline: 'LaTeX formulas rendered to SVG or PNG from a URL.',
    group: 'computing',
    brand: '#a21caf',
    brandAlt: '#a16207',
    mark: { plate: '#a21caf', accent: '#facc15' },
  },
  {
    id: 'lcao',
    name: { lead: 'lcao', alt: 'cheminfo', dot: true },
    host: 'lcao.cheminfo.org',
    repository: 'https://github.com/cheminfo/lcao.cheminfo.org',
    tagline: 'Combine atomic orbitals into molecular ones.',
    group: 'basics',
    brand: '#1565c0',
    brandAlt: '#c62828',
    mark: { plate: '#ffffff', accent: '#c62828', edge: '#dfe3e8' },
  },
  {
    id: 'regexp',
    name: { lead: 'regexp', alt: 'cheminfo', dot: true },
    host: 'regexp.cheminfo.org',
    repository: 'https://github.com/cheminfo/regexp.cheminfo.org',
    publicRepository: true,
    tagline: 'Learn regular expressions in a live playground.',
    group: 'computing',
    brand: '#1e3a8a',
    brandAlt: '#a16207',
    mark: { plate: '#1e3a8a', accent: '#fde047' },
  },
  {
    id: 'pdb',
    name: { lead: 'pdb', alt: 'cheminfo', dot: true },
    host: 'pdb.cheminfo.org',
    repository: 'https://github.com/cheminfo/pdb.cheminfo.org',
    publicRepository: true,
    tagline: 'A fast look at any Protein Data Bank entry.',
    group: 'research',
    brand: '#2563eb',
    brandAlt: '#b45309',
    mark: { plate: '#2563eb', accent: '#fbbf24' },
  },
  {
    id: 'elucidation',
    name: { lead: 'elucidation', alt: 'cheminfo', dot: true },
    host: 'elucidation.cheminfo.org',
    repository: 'https://github.com/cheminfo/elucidation.cheminfo.org',
    publicRepository: true,
    tagline: 'A structure from a 1H NMR spectrum and a formula.',
    group: 'spectra',
    brand: '#7e22ce',
    brandAlt: '#b45309',
    mark: { plate: '#7e22ce', accent: '#f59e0b' },
  },
  {
    id: 'equilibrium',
    name: { lead: 'Equi', alt: 'Librium' },
    host: 'equilibrium.cheminfo.org',
    repository: 'https://github.com/cheminfo/equilibrium.cheminfo.org',
    tagline: 'Chemical equilibria: pH, speciation and titration curves.',
    group: 'basics',
    brand: '#0b5754',
    brandAlt: '#a56600',
    mark: { plate: '#0b5754', accent: '#f2a71b' },
  },
  {
    id: 'polycarp',
    name: { lead: 'Poly', alt: 'Carp' },
    host: 'polycarp.cheminfo.org',
    repository: 'https://github.com/cheminfo/polycarp.cheminfo.org',
    publicRepository: true,
    tagline: 'Predict the microstructure of a radical copolymerisation.',
    group: 'research',
    brand: '#701a75',
    brandAlt: '#4d7c0f',
    mark: { plate: '#701a75', accent: '#a3e635' },
  },
  {
    id: '3d',
    name: { lead: '3d', alt: 'cheminfo', dot: true },
    host: '3d.cheminfo.org',
    repository: 'https://github.com/cheminfo/3d.cheminfo.org',
    tagline: 'Conformers in 3D from a structure you draw.',
    group: 'structures',
    brand: '#155e75',
    brandAlt: '#b45309',
    mark: { plate: '#155e75', accent: '#f97316' },
  },
  {
    id: 'periodic-table',
    name: { lead: 'Periodic', alt: 'Table' },
    host: 'periodic-table.cheminfo.org',
    repository: 'https://github.com/cheminfo/periodic-table.cheminfo.org',
    tagline: 'The periodic table, coloured, plotted and taken apart.',
    group: 'basics',
    brand: '#15803d',
    brandAlt: '#a16207',
    mark: { plate: '#15803d', accent: '#fbbf24' },
  },
  {
    id: 'database',
    name: { lead: 'database', alt: 'cheminfo', dot: true },
    host: 'database.cheminfo.org',
    repository: 'https://github.com/cheminfo/database.cheminfo.org',
    publicRepository: true,
    tagline: 'Query a real chemical dataset in SQL and in Mango.',
    group: 'research',
    brand: '#7c2d12',
    brandAlt: '#0b6e85',
    mark: { plate: '#7c2d12', accent: '#06b6d4' },
  },
  {
    id: 'symmetry',
    name: { lead: 'Symme', alt: 'Try' },
    host: 'symmetry.cheminfo.org',
    repository: 'https://github.com/cheminfo/symmetry.cheminfo.org',
    publicRepository: true,
    tagline: 'Find the symmetry of a molecule, a crystal or a pattern.',
    group: 'basics',
    brand: '#9f1239',
    // The gold that carries the apex of the mark sits at 2.2:1 on white, so
    // the second half of the wordmark takes this darkened amber instead.
    brandAlt: '#b45309',
    mark: { plate: '#9f1239', accent: '#f59e0b' },
  },
  {
    id: 'osiris',
    name: { lead: 'osiris', alt: 'cheminfo', dot: true },
    host: 'osiris.cheminfo.org',
    repository: 'https://github.com/cheminfo/osiris.cheminfo.org',
    publicRepository: true,
    tagline: 'Predicted toxicity risks and properties, one molecule or many.',
    group: 'research',
    brand: '#854d0e',
    // The lapis and the gold are equiluminant — 1.02:1 against each other — so
    // the mark draws the same blue lightened, and this darkened form is what
    // the second half of the wordmark is set in.
    brandAlt: '#1d4ed8',
    mark: { plate: '#854d0e', accent: '#60a5fa' },
  },
];

/**
 * The address of a site, which is its host over https.
 * @param site - The site being linked to.
 * @returns The URL to open.
 */
export function siteUrl(site: SiteRecord): string {
  return `https://${site.host}/`;
}
